Add lifecycle rule to abort multipart uploads on logging bucket (HCL1)
rackspace-infrastructure-automation/aws-terraform-alb pull request #28
Opened 2020-10-22 21:55 UTC by johnctitus

##### Corresponding Issue(s):
 - https://jira.rax.io/browse/MPCSUPENG-1601 (HCL1)

##### Summary of change(s):
Adds  S3 lifecycle rule to cleanup Multipart uploads on logging bucket to prevent drift when rule is applied by automation that creates this rule on existing buckets

##### Reason for Change(s):

- Eliminate manual drift within the IaC managed environment

##### Will the change trigger resource destruction or replacement? If yes, please provide justification:
No
##### Does this update/change involve issues with other external modules? If so, please describe the scenario.
No
##### If input variables or output variables have changed or has been added, have you updated the README?
Yes
##### Do examples need to be updated based on changes?
No
##### Note to the PR requester about Closing PR's
Please message the person that opened the issue when auto closing it on slack, as well as any other stakeholders of deep interest. Only close the issue if you believe that the issue is fully resolved with this PR.

#### This PR may auto close the issue associated with it. If you feel the issue is not resolved please reopen the issue.

2020-10-23 17:16 UTC, gdelvalle requested changes
I think we forgot to flip this boolean

2020-10-23 17:16 UTC, gdelvalle commented on main.tf
> +    enabled                                = false
i assume we meant `true` here

2020-10-26 13:11 UTC, johnctitus commented on main.tf
> +    enabled                                = false
Good catch.  Fixed.

2020-10-26 18:32 UTC, gdelvalle approved these changes

2020-10-27 21:11 UTC, bohn002 approved these changes

2020-10-27 22:11 UTC, merged